/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cabinet;

import DOM.ConnectionDataBase;
import cabinet.GestionPatient.MenuGestionPatient;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        if(ConnectionDataBase.Connection() != null){
            JOptionPane.showMessageDialog(null, "Connecter", "Alerte", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        BtnGerePatient = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btnRdv = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        btnPai = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cabinet organizer");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(new java.awt.Dimension(518, 423));
        getContentPane().setLayout(new java.awt.GridLayout(3, 1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("SF Compact Rounded", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/dentistry.png"))); // NOI18N
        jLabel1.setText("  Cabinet Organizer");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(0, 1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        BtnGerePatient.setBackground(new java.awt.Color(255, 255, 255));
        BtnGerePatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/BgGerePatient.png"))); // NOI18N
        BtnGerePatient.setBorderPainted(false);
        BtnGerePatient.setContentAreaFilled(false);
        BtnGerePatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnGerePatientMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnGerePatientMouseEntered(evt);
            }
        });
        BtnGerePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGerePatientActionPerformed(evt);
            }
        });
        BtnGerePatient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                OnclickGerePatient(evt);
            }
        });
        jPanel6.add(BtnGerePatient);

        jPanel4.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        btnRdv.setBackground(new java.awt.Color(255, 255, 255));
        btnRdv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/BgGereRdv.png"))); // NOI18N
        btnRdv.setBorderPainted(false);
        btnRdv.setContentAreaFilled(false);
        btnRdv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRdvMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRdvMouseEntered(evt);
            }
        });
        btnRdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRdvActionPerformed(evt);
            }
        });
        jPanel7.add(btnRdv);

        jPanel4.add(jPanel7);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        btnPai.setBackground(new java.awt.Color(255, 255, 255));
        btnPai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/btnPai.png"))); // NOI18N
        btnPai.setBorderPainted(false);
        btnPai.setContentAreaFilled(false);
        btnPai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPaiMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPaiMouseEntered(evt);
            }
        });
        btnPai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaiActionPerformed(evt);
            }
        });
        jPanel8.add(btnPai);

        jPanel4.add(jPanel8);

        jPanel2.add(jPanel4);

        getContentPane().add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/bgOut.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/BgSetting.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(479, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel3);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGerePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGerePatientActionPerformed
       this.setVisible(false);
        new MenuGestionPatient().setVisible(true); 
    }//GEN-LAST:event_BtnGerePatientActionPerformed

    private void OnclickGerePatient(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_OnclickGerePatient
        
    }//GEN-LAST:event_OnclickGerePatient

    private void btnRdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRdvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRdvActionPerformed

    private void btnPaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPaiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtnGerePatientMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnGerePatientMouseEntered
       BtnGerePatient.setIcon(new ImageIcon("src/Media/BgGerePatientClick.png"));
    }//GEN-LAST:event_BtnGerePatientMouseEntered

    private void BtnGerePatientMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnGerePatientMouseExited
         BtnGerePatient.setIcon(new ImageIcon("src/Media/BgGerePatient.png"));
    }//GEN-LAST:event_BtnGerePatientMouseExited

    private void btnRdvMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRdvMouseEntered
         btnRdv.setIcon(new ImageIcon("src/Media/BgGereRdvClick.png"));
    }//GEN-LAST:event_btnRdvMouseEntered

    private void btnRdvMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRdvMouseExited
        btnRdv.setIcon(new ImageIcon("src/Media/BgGereRdv.png"));
    }//GEN-LAST:event_btnRdvMouseExited

    private void btnPaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPaiMouseEntered
       btnPai.setIcon(new ImageIcon("src/Media/BtnPaiClick.png"));
    }//GEN-LAST:event_btnPaiMouseEntered

    private void btnPaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPaiMouseExited
        btnPai.setIcon(new ImageIcon("src/Media/BtnPai.png"));
    }//GEN-LAST:event_btnPaiMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Mac OS X".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Menu().setVisible(true);
            System.out.println("pause");
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGerePatient;
    private javax.swing.JButton btnPai;
    private javax.swing.JButton btnRdv;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
