/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cabinet.GestionPatient.Fiche;

import javax.swing.ImageIcon;

/**
 *
 * @author admin
 */
public class Fiche extends javax.swing.JFrame {

    /**
     * Creates new form Fiche
     */
    public Fiche() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btn_dent_11 = new javax.swing.JButton();
        btn_dent_12 = new javax.swing.JButton();
        brn_dent_13 = new javax.swing.JButton();
        btn_dent_14 = new javax.swing.JButton();
        btn_dent_15 = new javax.swing.JButton();
        btn_dent_16 = new javax.swing.JButton();
        btn_dent_17 = new javax.swing.JButton();
        btn_dent_18 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel3.setLayout(null);

        btn_dent_11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Dent/dent11droit.png"))); // NOI18N
        btn_dent_11.setBorderPainted(false);
        btn_dent_11.setContentAreaFilled(false);
        btn_dent_11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dent_11ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_dent_11);
        btn_dent_11.setBounds(140, 50, 50, 32);

        btn_dent_12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Dent/dent12droit.png"))); // NOI18N
        btn_dent_12.setBorderPainted(false);
        btn_dent_12.setContentAreaFilled(false);
        jPanel3.add(btn_dent_12);
        btn_dent_12.setBounds(110, 60, 60, 32);

        brn_dent_13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Dent/dent13droit.png"))); // NOI18N
        brn_dent_13.setBorderPainted(false);
        brn_dent_13.setContentAreaFilled(false);
        jPanel3.add(brn_dent_13);
        brn_dent_13.setBounds(100, 80, 50, 32);

        btn_dent_14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Dent/dent14droit.png"))); // NOI18N
        btn_dent_14.setBorderPainted(false);
        btn_dent_14.setContentAreaFilled(false);
        jPanel3.add(btn_dent_14);
        btn_dent_14.setBounds(90, 100, 40, 32);

        btn_dent_15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Dent/dent15droit.png"))); // NOI18N
        btn_dent_15.setBorderPainted(false);
        btn_dent_15.setContentAreaFilled(false);
        jPanel3.add(btn_dent_15);
        btn_dent_15.setBounds(70, 120, 50, 32);

        btn_dent_16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Dent/dent16droit.png"))); // NOI18N
        btn_dent_16.setBorderPainted(false);
        btn_dent_16.setContentAreaFilled(false);
        btn_dent_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dent_16ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_dent_16);
        btn_dent_16.setBounds(50, 140, 60, 50);

        btn_dent_17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Dent/dent17droit.png"))); // NOI18N
        btn_dent_17.setBorderPainted(false);
        btn_dent_17.setContentAreaFilled(false);
        btn_dent_17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dent_17MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_dent_17MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_dent_17MouseEntered(evt);
            }
        });
        jPanel3.add(btn_dent_17);
        btn_dent_17.setBounds(40, 180, 60, 40);

        btn_dent_18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Dent/dent18droit.png"))); // NOI18N
        btn_dent_18.setBorderPainted(false);
        btn_dent_18.setContentAreaFilled(false);
        btn_dent_18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dent_18MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_dent_18MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_dent_18MouseEntered(evt);
            }
        });
        jPanel3.add(btn_dent_18);
        btn_dent_18.setBounds(20, 210, 70, 32);

        jPanel4.setLayout(null);

        jButton10.setText("jButton10");
        jPanel4.add(jButton10);
        jButton10.setBounds(0, 30, 50, 29);

        jButton12.setText("jButton12");
        jPanel4.add(jButton12);
        jButton12.setBounds(50, 50, 50, 29);

        jButton13.setText("jButton13");
        jPanel4.add(jButton13);
        jButton13.setBounds(70, 80, 60, 29);

        jButton14.setText("jButton14");
        jPanel4.add(jButton14);
        jButton14.setBounds(80, 110, 70, 29);

        jButton15.setText("jButton15");
        jPanel4.add(jButton15);
        jButton15.setBounds(100, 140, 70, 29);

        jButton9.setText("jButton9");
        jPanel4.add(jButton9);
        jButton9.setBounds(130, 170, 60, 29);

        jButton11.setText("jButton11");
        jPanel4.add(jButton11);
        jButton11.setBounds(150, 200, 60, 29);

        jButton16.setText("jButton16");
        jPanel4.add(jButton16);
        jButton16.setBounds(161, 230, 70, 29);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 62, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dent_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dent_16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dent_16ActionPerformed

    private void btn_dent_11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dent_11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dent_11ActionPerformed

    private void btn_dent_18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dent_18MouseEntered
       btn_dent_18.setIcon(new ImageIcon("src/Media/Dent/dent_18_droit_hover.png"));
    }//GEN-LAST:event_btn_dent_18MouseEntered

    private void btn_dent_18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dent_18MouseExited
        btn_dent_18.setIcon(new ImageIcon("src/Media/Dent/dent18droit.png"));
    }//GEN-LAST:event_btn_dent_18MouseExited

    private void btn_dent_18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dent_18MouseClicked
        btn_dent_18.setIcon(new ImageIcon("src/Media/Dent/dent_18_droit_select.png"));
    }//GEN-LAST:event_btn_dent_18MouseClicked

    private void btn_dent_17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dent_17MouseClicked
        btn_dent_17.setIcon(new ImageIcon("src/Media/Dent/dent_17_droit_select.png"));
    }//GEN-LAST:event_btn_dent_17MouseClicked

    private void btn_dent_17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dent_17MouseEntered
        btn_dent_17.setIcon(new ImageIcon("src/Media/Dent/dent_17_droit_hover.png"));
    }//GEN-LAST:event_btn_dent_17MouseEntered

    private void btn_dent_17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dent_17MouseExited
        btn_dent_17.setIcon(new ImageIcon("src/Media/Dent/dent17droit.png"));
    }//GEN-LAST:event_btn_dent_17MouseExited

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fiche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fiche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fiche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fiche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fiche().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brn_dent_13;
    private javax.swing.JButton btn_dent_11;
    private javax.swing.JButton btn_dent_12;
    private javax.swing.JButton btn_dent_14;
    private javax.swing.JButton btn_dent_15;
    private javax.swing.JButton btn_dent_16;
    private javax.swing.JButton btn_dent_17;
    private javax.swing.JButton btn_dent_18;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
